export const TICKETS_FETCH_START = 'TICKET_FETCH_START'
export const TICKETS_FETCH_SUCCESS = 'TICKETS_FETCH_SUCCESS'
export const TICKETS_FETCH_FAIL = 'TICKETS_FETCH_FAIL'

export const RATES_FETCH_START = 'RATES_FETCH_START'
export const RATES_FETCH_SUCCESS = 'RATES_FETCH_SUCCESS'
export const RATES_FETCH_FAIL = 'RATES_FETCH_FAIL'
export const RATES_CHANGE_RATE = 'RATES_CHANGE_RATE'
